CREATE TABLE IF NOT EXISTS student (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  studentName VARCHAR(100) NOT NULL,
  groupId INTEGER NOT NULL,
  FOREIGN KEY (groupId) REFERENCES studentGroup (idGroup)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS studentGroup (
  idGroup INTEGER PRIMARY KEY AUTOINCREMENT,
  groupName VARCHAR(45) NOT NULL);

CREATE TABLE IF NOT EXISTS teachers (
  idTeachers INTEGER PRIMARY KEY AUTOINCREMENT,
  teacherName VARCHAR(45) NOT NULL
  );

CREATE TABLE IF NOT EXISTS subjects (
  idSubject INTEGER PRIMARY KEY AUTOINCREMENT,
  subjectName VARCHAR(45) NOT NULL,
  idTeacher INTEGER NOT NULL,
  FOREIGN KEY (idTeacher) REFERENCES teachers (idTeachers)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS scoreboard (
  idTable INTEGER PRIMARY KEY AUTOINCREMENT,
  idSubject INTEGER NOT NULL,
  idStudent INTEGER NOT NULL,
  markDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  mark TINYINT NOT NULL,
    FOREIGN KEY (idSubject) REFERENCES subjects (idSubject)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (idStudent) REFERENCES student (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
